# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo',
        ),
    ]
